### ISSUE TITLE
Bpipe error

### ISSUE THREAD

**Issue by Marina-Blmz** [CoBrALab/MAGeTDocker#8]
Hej Gab,

trying to run bpipe from this container. 

The command i am running:` bpipe run -n 4 pipeline.bpipe *mnc` 

The error I am getting:

```
=========================================== Bpipe Error ============================================

An error occurred executing your pipeline:

                   Cannot run program "qsub": error=2, No such file or directory                    


Please see the details below for more information.

"========================================== Error Details ===========================================

java.io.IOException: Cannot run program "qsub": error=2, No such file or directory
	at bpipe.Utils.executeCommand(Utils.groovy:944)
	at bpipe.Utils.executeCommand(Utils.groovy)
	at bpipe.Utils$executeCommand$12.call(Unknown Source)
	at bpipe.executor.SgeCommandExecutor.start(SgeCommandExecutor.groovy:165)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.executor.ThrottledDelegatingCommandExecutor.doStart(ThrottledDelegatingCommandExecutor.groovy:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.executor.ThrottledDelegatingCommandExecutor.start(ThrottledDelegatingCommandExecutor.groovy:94)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.CommandManager.start(CommandManager.groovy:149)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineContext.async(PipelineContext.groovy:2304)
	at bpipe.PipelineContext.async(PipelineContext.groovy)
	at bpipe.PipelineContext.execImpl(PipelineContext.groovy:1841)
	at bpipe.PipelineContext.exec(PipelineContext.groovy:1826)
	at bpipe.PipelineContext.exec(PipelineContext.groovy)
	at bpipe.PipelineContext.exec(PipelineContext.groovy:1792)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineContext.invokeMethod(PipelineContext.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineDelegate.methodMissing(PipelineDelegate.groovy:163)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineDelegate.invokeMethod(PipelineDelegate.groovy)
	at minc-library.bpipe$_run_closure1$_closure24.doCall(minc-library.bpipe.bpipe:45)
	at minc-library.bpipe$_run_closure1$_closure24.doCall(minc-library.bpipe.bpipe)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineContext.produceImpl(PipelineContext.groovy:1461)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineContext.produceImpl(PipelineContext.groovy:1251)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.TransformOperation$_execute_closure1.doCall(TransformOperation.groovy:208)
	at bpipe.TransformOperation$_execute_closure1.doCall(TransformOperation.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineContext.withInputs(PipelineContext.groovy:2689)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.TransformOperation.execute(TransformOperation.groovy:207)
	at bpipe.TransformOperation.to(TransformOperation.groovy:179)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.TransformOperation.to(TransformOperation.groovy:89)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at minc-library.bpipe$_run_closure1.doCall(minc-library.bpipe.bpipe:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineCategory$_plus_closure4.doCall(PipelineCategory.groovy:189)
	at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineCategory$_plus_closure4.doCall(PipelineCategory.groovy:189)
	at jdk.internal.reflect.GeneratedMethodAccessor164.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineCategory$_plus_closure4.doCall(PipelineCategory.groovy:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineCategory$_plus_closure4.doCall(PipelineCategory.groovy:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineCategory$_plus_closure4.doCall(PipelineCategory.groovy:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineCategory$_plus_closure4.doCall(PipelineCategory.groovy:189)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.invokeMethod(PipelineStage.groovy)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy:383)
	at bpipe.PipelineStage$_runWrappedBody_closure2.doCall(PipelineStage.groovy)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at bpipe.PipelineStage.runWrappedBody(PipelineStage.groovy:382)
	at bpipe.PipelineStage.runBody(PipelineStage.groovy:357)
	at bpipe.PipelineStage.run(PipelineStage.groovy:241)
	at bpipe.PipelineStage$run.call(Unknown Source)
	at bpipe.Pipeline.runSegment(Pipeline.groovy:643)
	at bpipe.BranchRunner.run(BranchRunner.groovy:69)
Caused by: java.io.IOException: error=2, No such file or directory
	... 157 more"
```

Not sure if it's me doing smth wrong or a bug, but reporting in a case it might be the latter.

Thank you in any case!

**Comment by gdevenyi** [comment]
Looks like you probably have the residual `bpipe.config` file from `minc-bpipe-library` which is turning on the job submission, which is not available in the container. You will need to remove it.
